# Generated by Django 4.0.2 on 2022-03-02 14:25

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store', validators=[store.validators.validate_image_size]),
        ),
    ]
